from django.db import models
from django.shortcuts import get_object_or_404

class Gallery1990(models.Model):
    rowid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    address_number = models.CharField(max_length=100) 
    address_direction = models.CharField(max_length=100) 
    address_street = models.CharField(max_length=100) 
    address_type = models.CharField(max_length=100) 
    address_zip = models.CharField(max_length=100) 
    start_year = models.IntegerField()
    end_year = models.IntegerField()
    count_90 = models.CharField(max_length=100) 
    count_95 = models.CharField(max_length=100) 
    count_00 = models.CharField(max_length=100) 
    count_05 = models.CharField(max_length=100) 
    count_10 = models.CharField(max_length=100) 
    director = models.CharField(max_length=100) 
    painting = models.CharField(max_length=20) 
    outcome = models.CharField(max_length=100) 
    sculpture = models.CharField(max_length=20) 
    notes = models.CharField(max_length=400) 
    three_d_construction = models.CharField(max_length=20) 
    pastels = models.CharField(max_length=20) 
    furniture = models.CharField(max_length=20) 
    ceramics = models.CharField(max_length=20) 
    glass = models.CharField(max_length=20) 
    metal = models.CharField(max_length=20) 
    prints = models.CharField(max_length=20) 
    photography = models.CharField(max_length=20) 
    drawing = models.CharField(max_length=20) 
    jewelry = models.CharField(max_length=20) 
    wearables = models.CharField(max_length=20) 
    accessories = models.CharField(max_length=20) 
    cards = models.CharField(max_length=20) 
    lithography = models.CharField(max_length=20) 
    etching = models.CharField(max_length=20) 
    serigraphy = models.CharField(max_length=20) 
    monoprints = models.CharField(max_length=20) 
    folk_art = models.CharField(max_length=20) 
    graphics = models.CharField(max_length=20) 
    fiber = models.CharField(max_length=20) 
    handcrafts = models.CharField(max_length=20) 
    mixed_media = models.CharField(max_length=20) 
    all = models.CharField(max_length=20) 
    tapestry = models.CharField(max_length=20) 
    clay = models.CharField(max_length=20) 
    wood = models.CharField(max_length=20) 
    kaleidoscopes = models.CharField(max_length=20) 
    silkscreen = models.CharField(max_length=20) 
    mobiles = models.CharField(max_length=20) 
    assemblage = models.CharField(max_length=20) 
    neon = models.CharField(max_length=20) 
    collage = models.CharField(max_length=20) 
    enamel = models.CharField(max_length=20) 
    porcelain = models.CharField(max_length=20) 
    books = models.CharField(max_length=20) 
    fresco = models.CharField(max_length=20) 
    pottery = models.CharField(max_length=20) 
    weaving = models.CharField(max_length=20) 
    basketry = models.CharField(max_length=20) 
    leather = models.CharField(max_length=20) 
    batik = models.CharField(max_length=20) 
    paper = models.CharField(max_length=20) 
    move1 = models.CharField(max_length=100) 
    move2 = models.CharField(max_length=100) 
    move3 = models.CharField(max_length=100) 
    lat = models.DecimalField(max_digits=15, decimal_places=20) 
    lan = models.DecimalField(max_digits=15, decimal_places=20) 
    neighborhood = models.CharField(max_length=100) 
    class Meta:
        db_table = u'galleries1990'
        ordering = ["name"]

    def __unicode__(self):
        return self.name